# Generated by Django 4.0.10 on 2023-03-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallForPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('abstract', models.TextField()),
                ('pdf_url', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[(0, 'New'), (1, 'In Review'), (2, 'Accepted'), (3, 'Refused')], default=0, max_length=255)),
                ('call_for_papers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='proposals.callforpapers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=64)),
                ('reviewer_surname', models.CharField(max_length=64)),
                ('reviewer_email', models.CharField(max_length=64)),
                ('pdf_url', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[(0, 'Initial'), (1, 'Accepted'), (2, 'Minor Review'), (3, 'Major Review'), (4, 'Refused')], default=0, max_length=255)),
                ('proposal', models.ManyToManyField(related_name='articles', to='proposals.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposer',
            field=models.ManyToManyField(related_name='articles', to='proposals.proposer'),
        ),
    ]
