# Generated by Django 4.0.10 on 2023-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callforpapers',
            options={'verbose_name_plural': 'call for papers'},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Review'), (2, 'Accepted'), (3, 'Refused')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initial'), (1, 'Accepted'), (2, 'Minor Review'), (3, 'Major Review'), (4, 'Refused')]),
        ),
    ]
