# Generated by Django 4.1.7 on 2023-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalissues', '0003_alter_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='img_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
