# Generated by Django 4.0.10 on 2023-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalissues', '0004_alter_article_img_url_alter_issue_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='articles', to='journalissues.author'),
        ),
    ]
