# Generated by Django 4.0.10 on 2023-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalissues', '0008_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
