# Generated by Django 4.0.10 on 2023-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalissues', '0009_issue_date_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
